---
kind: pipeline
type: docker
name: app

steps:

- name: deploy_local
  pull: never
  image: ${DCAPE_COMPOSE}
  commands:
  - . setup config
  - . setup root
  - cp -pr nginx.conf $APP_ROOT/
  - make db-create
  - docker-compose up -d --force-recreate
  volumes:
  - name: dockersock
    path: /var/run/docker.sock

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
